apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: simpleapp-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: atychkivskyy/simpleapp-api
      labels:
        - self-hosted
        - linux
        - k8s
